---
abstract: 'XML stylesheet system'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Carp: 0
  Module::Build: 0.3601
  Test::Class: 0
  Test::Class::Load: 0
  Test::More: 0.94
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101590'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-XSS
requires:
  Moose: 0
  Moose::Exporter: 0
  Moose::Role: 0
  MooseX::AttributeHelpers: 0
  MooseX::ClassAttribute: 0
  MooseX::Clone: 0
  MooseX::SemiAffordanceAccessor: 0
  Scalar::Util: 0
  XML::LibXML: 0
  overload: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=XML-XSS
  homepage: http://search.cpan.org/dist/XML-XSS/
  repository: git://github.com/yanick/xml-xss.git
version: 0.1.3
